export const shelfCategories = [
  {
    name: "Abstract",
    direction: "right",
    color: "#C9A96E",
    glowColor: "rgba(201,169,110,0.35)",
    position: { top: "8%", left: "50%", width: "36%", transform: "translateX(-50%)" },
    artworks: [],
  },
  {
    name: "Illustration",
    direction: "left",
    color: "#E8C4C4",
    glowColor: "rgba(232,196,196,0.35)",
    position: { top: "74%", left: "50%", width: "60%", transform: "translateX(-50%)" },
    artworks: [],
  },
  {
    name: "Modern",
    direction: "right",
    color: "#8B9DC3",
    glowColor: "rgba(139,157,195,0.35)",
    position: { top: "28%", left: "50%", width: "40%", transform: "none" },
    artworks: [],
  },
  {
    name: "Minimalism",
    direction: "left",
    color: "#B0A8B9",
    glowColor: "rgba(176,168,185,0.35)",
    position: { top: "52%", right: "50%", width: "50%", transform: "none" },
    artworks: [],
  },
  {
    name: "Expressionism",
    direction: "right",
    color: "#D4896A",
    glowColor: "rgba(212,137,106,0.35)",
    position: { top: "52%", left: "50%", width: "45%", transform: "none" },
    artworks: [],
  },
  {
    name: "Landscape",
    direction: "left",
    color: "#7A9E7E",
    glowColor: "rgba(122,158,126,0.35)",
    position: { top: "28%", right: "50%", width: "43%", transform: "none" },
    artworks: [],
  },
];
